// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="Common Questions"
          title="Frequently Asked Questions"
          description="Get clear answers about our services."
          items={[
            {
              question: "What is Amazon Relay Dispatch?",
              answer: "Professional coordination for Amazon loads.",
            },
            {
              question: "How fast can I start?",
              answer: "Within 24 hours of onboarding.",
            },
            {
              question: "Are you 24/7?",
              answer: "Yes, dispatch support is constant.",
            },
            {
              question: "Do you work with owner-operators?",
              answer: "Yes, we focus on owner-operators.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
