// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "operations" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function OperationsSection(): React.JSX.Element {
  return (
    <div id="operations" data-section="operations">
        <SectionErrorBoundary name="operations">
              <MetricsSimpleCards
          tag="Live Operations"
          title="Operational Performance"
          description="Real-time metrics showing our dispatch impact."
          metrics={[
            {
              value: "$8,468",
              description: "Weekly Revenue",
            },
            {
              value: "$8,564",
              description: "Avg. Per Truck",
            },
            {
              value: "$8,468",
              description: "Weekly Revenue",
            },
            {
              value: "30+",
              description: "Weekly Revenue",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
