// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "process" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProcessSection(): React.JSX.Element {
  return (
    <div id="process" data-section="process">
        <SectionErrorBoundary name="process">
              <FeaturesRevealCardsBento
          tag="Why Choose Us"
          title="Our Dispatch Workflow"
          description="Drivers trust United Team because we focus on higher rates, honest communication, and professional support."
          items={[
            {
              title: "Carrier Onboarding",
              description: "Simple and fast digital setup.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/office-hardware_1098-14352.jpg",
            },
            {
              title: "Load Planning",
              description: "Strategic route optimization.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-relaxed-freelance-worker-listening-music-headphones-working-with-laptop-portrait-young-specialists-international-corporation-spending-time-light-cozy-office_197531-3785.jpg",
            },
            {
              title: "Rate Negotiation",
              description: "Best possible market rates.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/employees-coworker-with-disability-looking-figures-inclusive-office_482257-126236.jpg",
            },
            {
              title: "Dispatch Monitoring",
              description: "Proactive real-time tracking.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/businessman-walking-with-colleague-outside-office-building_107420-74360.jpg",
            },
            {
              title: "Delivery Tracking",
              description: "Automated status updates.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-employee-sending-text-messages-smartphone-work-chatting-social-media-coworking-space-sitting-workplace-desk-office-worker-chatting-telephone-typing-cellphone_482257-51244.jpg",
            },
            {
              title: "Performance Reports",
              description: "Detailed operational insights.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/call-center-staff-member-providing-step-by-step-guidance-customer_482257-125975.jpg",
            },
            {
              title: "Continuous Support",
              description: "Long-term partnership focus.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/people-taking-care-office-cleaning_23-2149374449.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
