// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesTaggedCards from '@/components/sections/features/FeaturesTaggedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesTaggedCards
          tag="Our Services"
          title="Dispatch Services"
          description="We specialize in Amazon Relay dispatch services throughout the United States, combining market expertise and exceptional communication."
          items={[
            {
              tag: "Relay",
              title: "Amazon Relay Dispatch",
              description: "Expert management of Amazon Relay loads.",
              primaryButton: {
                text: "Learn More",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/save-front-side_187299-44781.jpg",
            },
            {
              tag: "Support",
              title: "24/7 Operations",
              description: "Around the clock dispatcher support.",
              primaryButton: {
                text: "Get Support",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/customer-service-24-hours-7-days-support_53876-120656.jpg",
            },
            {
              tag: "Revenue",
              title: "Rate Negotiation",
              description: "Maximize every load revenue effectively.",
              primaryButton: {
                text: "Negotiate Rates",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/rate-contract-shaking-hands-graphic-heart_1134-1180.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
