// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamOverlayCards from '@/components/sections/team/TeamOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamOverlayCards
          tag="Leadership"
          title="Meet The Founders"
          description="Built by logistics experts."
          members={[
            {
              name: "Ismatov Temur",
              role: "Founder",
              imageSrc: "http://img.b2bpic.net/free-photo/young-businessman-happy-expression_1194-1551.jpg",
            },
            {
              name: "Subkhonov Umed",
              role: "Co-Founder",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-volunteers-with-boxes_23-2149196099.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
