// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialOverlayCards from '@/components/sections/testimonial/TestimonialOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialOverlayCards
          tag="Trust"
          title="What Our Partners Say"
          description="We build lasting relationships through excellence."
          testimonials={[
            {
              name: "John Doe",
              role: "CEO",
              company: "Mansur Logistics",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/friendly-handsome-business-leader-cafe_1262-3537.jpg",
            },
            {
              name: "Jane Smith",
              role: "Fleet Manager",
              company: "REM Express",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-person-working-call-center_23-2149288227.jpg",
            },
            {
              name: "Alex Rivera",
              role: "Owner",
              company: "Dale & R Inc",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/man-with-helmet-working-logistic_23-2148886807.jpg",
            },
            {
              name: "Sarah Lee",
              role: "Dispatch",
              company: "Nodir Corp",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-beautiful-happy-corporate-woman-suit-stands-street-smiles-poses-near-office_1258-193986.jpg",
            },
            {
              name: "David Kim",
              role: "Owner-Op",
              company: "Road Stars",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/young-stylish-asian-woman-business-owner-glasses-sitting-cafe-with-notebook-smiling-camera_1258-199055.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
